### ISSUE TITLE
custom_attribute fails without custom mapping

### ISSUE THREAD

**Issue by sinyello** [rundeck-plugins/docker#34]
It works with custom mapping. Comma separated not supported though (other issue). It fails without, lacking to fall back using default.

```
Traceback (most recent call last):
  File "/var/lib/rundeck/libext/cache/docker-container/model-source", line 273, in <module>
    mappingList
  File "/var/lib/rundeck/libext/cache/docker-container/model-source", line 170, in nodeCollectData
    if custom_attributes:
UnboundLocalError: local variable 'custom_attributes' referenced before assignment
ERROR ExceptionCatchingResourceModelSource: [ResourceModelSource: 1.source (docker-container-model-source), project: docker-container-test]
com.dtolabs.rundeck.core.resources.ResourceModelSourceException: failed to execute: /var/lib/rundeck/libext/cache/docker-container/model-source: Script execution failed with result: 1
	at com.dtolabs.rundeck.core.resources.ScriptPluginResourceModelSource.getNodes(ScriptPluginResourceModelSource.java:81)
	at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport$LoadedSource.getNodes(ProjectNodeSupport.java:456)
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:138)
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:365)
	at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
	at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes.call(Unknown Source)
	at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:44)
	at rundeck.services.nodes.CachedProjectNodes$reloadNodeSet.call(Unknown Source)
	at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy:290)
	at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy)
	at sun.reflect.GeneratedMethodAccessor1353.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at com.codahale.metrics.Timer$time$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at com.codahale.metrics.Timer$time$0.call(Unknown Source)
	at org.grails.plugins.metricsweb.MetricService.withTimer(MetricService.groovy:57)
	at sun.reflect.GeneratedMethodAccessor1352.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:144)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:104)
	at rundeck.services.NodeService.loadNodes(NodeService.groovy:302)
	at sun.reflect.GeneratedMethodAccessor1345.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:95)
	at rundeck.services.NodeService.this$dist$invoke$1(NodeService.groovy)
	at rundeck.services.NodeService$3.methodMissing(NodeService.groovy)
	at sun.reflect.GeneratedMethodAccessor908.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:951)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1227)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
	at rundeck.services.NodeService$3.invokeMethod(NodeService.groovy)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:398)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:338)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
	at rundeck.services.NodeService$3$_reload_closure1.doCall(NodeService.groovy:138)
	at rundeck.services.NodeService$3$_reload_closure1.doCall(NodeService.groovy)
	at sun.reflect.GeneratedMethodAccessor1524.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:271)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.dtolabs.rundeck.core.resources.ResourceModelSourceException: Script execution failed with result: 1
	at com.dtolabs.rundeck.core.resources.ScriptResourceUtil.executeScript(ScriptResourceUtil.java:147)
	at com.dtolabs.rundeck.core.resources.ScriptPluginResourceModelSource.getNodes(ScriptPluginResourceModelSource.java:67)
	... 70 more
```

**Comment by ltamaster** [comment]
Hi @sinyello 
It will be fixed on 1.4.1
