### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 14: ordinal not in range(128)

### ISSUE THREAD

**Issue by ilyavaiser** [rundeck-plugins/docker#64]
Traceback (most recent call last):
  File "/home/rundeck/libext/cache/docker-container-1.4.2/node-execute", line 100, in <module>
    print(line.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 14: ordinal not in range(128)
[docker-container-execute-command]: result code: 1
Failed: NonZeroResultCode: Script result code was: 1
[workflow] finishExecuteNodeStep(/production-backend_app-cron.1.ypfdug8lefrdju3dvda813pu8): NodeDispatch: NonZeroResultCode: Script result code was: 1

**Comment by henres** [comment]
Hello, I have a similar problem :

```
 [OK] Start
Traceback (most recent call last):
  File "/home/rundeck/libext/cache/docker-container-1.4.5/node-execute", line 100, in <module>
    print(line.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 18: ordinal not in range(128)
Failed: NonZeroResultCode: Script result code was: 1
```

**Comment by fdevans** [comment]
Sorry we missed this.  If it's still a problem please open a new Issue with current Rundeck version details, and a deeper description of how this can be repeated.
